### ISSUE TITLE
Enhancement: Improved CEEMDAN

### ISSUE THREAD

**Issue by chuckcoleman** [helske/Rlibeemd#2]
I don't think this will be difficult, given the short MATLAB source code available at http://bioingenieria.edu.ar/grupos/ldnlys/metorres/metorres_files/ceemdan_v2014.m.

Reference: Colominas MA, Schlotthauer G, Torres ME. "Improve complete ensemble EMD: A suitable tool for biomedical signal processing," Biomedical Signal Processing and Control, vol. 14, pp. 19-29 (2014)

**Comment by helske** [comment]
Thanks, looks interesting. It seems that you already made the same suggestion in the original `libeemd` repository, so I'm going to close this one.
