### ISSUE TITLE
Please release 1.4.3 with OpenMP support here

### ISSUE THREAD

**Issue by barracuda156** [helske/Rlibeemd#9]
CRAN recommends installing from GH, but no 1.4.3 here.

https://cran.r-project.org/web/packages/Rlibeemd/index.html
vs
https://github.com/helske/Rlibeemd/tags

**Comment by helske** [comment]
Thanks for the reminder, added a release here as well. Btw you can always install the latest github version as
```
devtools::install_github("helske/Rlibeemd")
```

**Comment by barracuda156** [comment]
@helske Thank you! (I maintain `Rlibeemd` port in Macports, so we need a tarball for that.)
